[build]
  command = "mkdir -p themes && ln -sfn $PWD themes/hugo-profile && cd exampleSite && hugo --gc --minify --themesDir ../themes -d ../public"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.147.0"
  HUGO_ENV = "production"
